esphome:
  name: garden-sensors

esp32:
  board: esp32dev
  framework:
    type: esp-idf

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret garden_sensors_api_key

ota:
  password: !secret garden_sensors_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garden-Sensors Fallback Hotspot"
    password: !secret garden_sensors_hotspot_password

captive_portal:

dallas:
  - pin: GPIO23

ads1115:
  - address: 0x48

sensor:
  - platform: dallas
    address: 0x2b03019794341228
    name: "Tank Right Temperature"
    unit_of_measurement: "°C"
  - platform: dallas
    address: 0x5b030e979460de28
    name: "Tank Left Temperature"
    unit_of_measurement: "°C"
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 2.048 # up to 2.048V
    name: "Tank Right Depth"
    unit_of_measurement: "mm"
    filters:
      # depth = ((voltage * to_mV / 120_ohm) - current_init_mA) * (range_mm / water_density / 16.0)
      - lambda: return ((x * 1000.0 / 120.0) - 4.0) * (5000.0 / 1.0 / 16.0);
  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 2.048 # up to 2.048V
    name: "Tank Left Depth"
    unit_of_measurement: "mm"
    filters:
      # depth = ((voltage * to_mV / 120_ohm) - current_init_mA) * (range_mm / water_density / 16.0)
      - lambda: return ((x * 1000.0 / 120.0) - 4.0) * (5000.0 / 1.0 / 16.0);

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: garden_sensors
  password: !secret garden_sensors_mqtt_password
  birth_message:
    topic: garden-sensors/status
    payload: online
  will_message:
    topic: garden-sensors/status
    payload: offline
  idf_send_async: true
  skip_cert_cn_check: false
  <<: !include letsencrypt_chain.yaml
