substitutions:
  device_name: seedlings-sensors
  device_id: seedlings_sensors
  friendly_name: Seedlings Sensors
  device_description: Sensors and thermostat control for seedlings

esphome:
  name: ${device_name}
  comment: ${device_description}

esp32:
  board: m5stick-c
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret seedlings_sensors_api_key

ota:
  password: !secret seedlings_sensors_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Seedlings Fallback Hotspot"
    password: !secret seedlings_sensors_hotspot_password

captive_portal:

external_components:
  - source: github://airy10/esphome-m5stickC
    components: [axp192]

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: True

dallas:
  - pin: GPIO32 # grove port

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"

  # AXP192 power management - must be present to initialize TFT power on
  - platform: axp192
    address: 0x34
    i2c_id: bus_a
    update_interval: 30s
    battery_level:
      name: "${friendly_name} Battery Level"
      id: "${device_id}_batterylevel"

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

  - platform: dallas
    id: seedlings_air_temperature_sensor
    address: 0xec0301979421a028
    name: "Seedlings Air Temperature"
    unit_of_measurement: "°C"

  - platform: dallas
    id: seedlings_water_temperature_sensor
    address: 0xb4030a97945e8a28
    name: "Seedlings Water Temperature"
    unit_of_measurement: "°C"

switch:
  - platform: template
    name: "Thermostat Is Heating"
    optimistic: true
    internal: true
    id: thermostat_is_heating

climate:
  - platform: thermostat
    id: seedlings_thermostat
    name: "Heating Mat Controller"
    sensor: seedlings_air_temperature_sensor
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s

    heat_action:
      - switch.turn_on: thermostat_is_heating
      - mqtt.publish:
          topic: !secret seedlings_sensors_mqtt_command_topic
          payload: !secret seedlings_sensors_mqtt_heater_on_payload
    idle_action:
      - switch.turn_off: thermostat_is_heating
      - mqtt.publish:
          topic: !secret seedlings_sensors_mqtt_command_topic
          payload: !secret seedlings_sensors_mqtt_heater_off_payload

    default_preset: Home
    preset:
      - name: Home
        mode: heat
        default_target_temperature_low: 25 °C
    visual:
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret seedlings_sensors_mqtt_username
  password: !secret seedlings_sensors_mqtt_password
  birth_message:
    topic: seedlings-sensors/status
    payload: online
  will_message:
    topic: seedlings-sensors/status
    payload: offline
  idf_send_async: true
  skip_cert_cn_check: false
  <<: !include letsencrypt_chain.yaml

font:
  - file: 'fonts/OpenSans-Regular.ttf'
    id: big_font
    size: 50
  - file: 'fonts/OpenSans-Regular.ttf'
    id: small_font
    size: 25

color:
    - id: bg_off
      red: 0%
      green: 0%
      blue: 0%
    - id: bg_on
      red: 100%
      green: 50%
      blue: 00%
    - id: color_off
      red: 50%
      green: 50%
      blue: 50%
    - id: color_on
      red: 0%
      green: 0%
      blue: 0%

# https://devices.esphome.io/devices/M5Stack-M5StickC-PLUS
display:
  - platform:  st7789v
    model: TTGO TDisplay 135x240
    cs_pin: GPIO5
    dc_pin: GPIO23
    reset_pin: GPIO18
    rotation: 270
    lambda: |-
      if (id(thermostat_is_heating).state) {
        it.fill(id(bg_on));
        it.print(10, 35, id(big_font), id(color_on), TextAlign::TOP_LEFT, "ON");
        it.printf(230, 20, id(small_font), id(color_on), TextAlign::TOP_RIGHT, "S: %.1f°C", id(seedlings_thermostat).target_temperature);
        it.printf(230, 50, id(small_font), id(color_on), TextAlign::TOP_RIGHT, "A: %.1f°C", id(seedlings_air_temperature_sensor).state);
        it.printf(230, 80, id(small_font), id(color_on), TextAlign::TOP_RIGHT, "W: %.1f°C", id(seedlings_water_temperature_sensor).state);
      } else {
        it.fill(id(bg_off));
        it.print(10, 35, id(big_font), id(color_off), TextAlign::TOP_LEFT, "OFF");
        it.printf(230, 20, id(small_font), id(color_off), TextAlign::TOP_RIGHT, "S: %.1f°C", id(seedlings_thermostat).target_temperature);
        it.printf(230, 50, id(small_font), id(color_off), TextAlign::TOP_RIGHT, "A: %.1f°C", id(seedlings_air_temperature_sensor).state);
        it.printf(230, 80, id(small_font), id(color_off), TextAlign::TOP_RIGHT, "W: %.1f°C", id(seedlings_water_temperature_sensor).state);
      }
